version: '2'
services:
  web:
    build: .
    ports:
      - "7000:7000"
    links:
      - 'rethinkdb'
      - 'redis'
    environment:
      - HELLO=anton2
      - RETHINKDB=rethinkdb
      - PORT=7000
      - REDIS_HOST=redis
  rethinkdb:
    image: rethinkdb
    ports:
        - "8080"
        - "28015"
        - "29015"
  redis:
    image: "redis"    
  redis2:
    image: "redis"   
  redis3:
    image: "redis"       
