version: '2'
services:
  web:
    build: .
    environment:
      - RETHINKDB=rethinkdb
      - PORT=9000
      - REDIS_HOST=redis
      - NAME=main
    links:
      - 'rethinkdb'
      - 'redis'         
  rethinkdb:
    image: rethinkdb
    ports:
        - "8080"
        - "28015"
        - "29015"
  redis:
    image: "redis"
  redis3:
    image: "redis"
