 version: '2'
 services:
  web:
    extends:
      file: docker-compose.yml
      service: web
    ports:
      - "9000:9000"
    environment:
      - NAME=extended-updated1
  redis0:
   image: "redis"
